name: Static code checkers

on: [push]

permissions: {}

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ./.github/actions/uv-setup
      - name: Create a dummy data.py
        run: cp data.py-dist data.py
      - run: mypy --install-types --non-interactive lib/ conftest.py pkgfixtures.py tests/

  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ./.github/actions/uv-setup/
      - name: Create a dummy data.py
        run: cp data.py-dist data.py
      - run: pyright lib/ conftest.py pkgfixtures.py # tests/

  ruff:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: "1"
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ./.github/actions/uv-setup/
      - name: Create a dummy data.py
        run: cp data.py-dist data.py
      - run: ruff check conftest.py lib/ tests/

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ./.github/actions/uv-setup/
      - run: flake8
