name: GitHub Actions Security Analysis with zizmor ðŸŒˆ

on: [push]

permissions: {}

jobs:
  zizmor:
    name: zizmor latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # 6.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/uv-setup/
        with:
          sync: false
      - run: uvx zizmor --color=always .
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
